### PR TITLE
Fix todos

### LINKED ISSUE #71: addTODOsBroken
the add TODO feature in licenses portlet is probably broken

### PR DESCRIPTION
**Pull request by heydenreich**
Closes #71

### CODE REVIEW

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/licenses/LicensesPortlet.java [hunk 1]
```diff
@@ -92,14 +95,38 @@ public void doView(RenderRequest request, RenderResponse response) throws IOExce
             if (id != null) {
                 try {
                     LicenseService.Iface client = thriftClients.makeLicenseClient();
-                    License license = client.getByID(id, user.getDepartment());
-                    request.setAttribute(KEY_LICENSE_DETAIL, license);
+                    License moderationLicense = client.getByIDWithOwnModerationRequests(id, user.getDepartment(), user);
+
+                    List<Todo> addedTodos = moderationLicense.getTodos();
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/licenses/LicensesPortlet.java]: It might be better to write
```Java
[...]
List<Todo> allTodos = nullToEmptyList(moderationLicense.getTodos());
List<Todo> addedTodos = addedTodos
        .stream()
        .filter(todo -> todo.id.startsWith("tmp"))
        .collect(Collectors.toList());
List<Todo>  currentTodos =  currentTodos
        .stream()
        .filter(todo -> !todo.id.startsWith("tmp"))
        .collect(Collectors.toList());

request.setAttribute(ADDED_TODOS_FROM_MODERATION_REQUEST, addedTodos);
request.setAttribute(DB_TODOS_FROM_MODERATION_REQUEST,currentTodos);
[...]
```

File: backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java [hunk 2]
```diff
@@ -247,7 +244,8 @@ public Project getProjectByIdforEdit(String id, User user) throws SW360Exception
         } else {
             final String email = user.getEmail();
             Optional<ModerationRequest> moderationRequestOptional = CommonUtils.getFirstModerationRequestOfUser(moderationRequestsForDocumentId, email);
-            if (moderationRequestOptional.isPresent()) {
+            if (moderationRequestOptional.isPresent()
+                    && (moderationRequestOptional.get().getModerationState().equals(ModerationState.INPROGRESS)|| moderationRequestOptional.get().getModerationState().equals(ModerationState.PENDING))) {
```
Comment (maximilianhuber) [inline backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java]: This line is too long

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 3]
```diff
@@ -115,25 +121,67 @@ public LicenseDatabaseHandler(String url, String dbName) throws MalformedURLExce
...
+        DocumentState documentState;
+
+        if (moderationRequestsForDocumentId.isEmpty()) {
+            license = getLicenseForOrganisation(id, organisation);
+
+            documentState = CommonUtils.getOriginalDocumentState();
+        } else {
+
+            final String email = user.getEmail();
+            com.google.common.base.Optional<ModerationRequest> moderationRequestOptional = CommonUtils.getFirstModerationRequestOfUser(moderationRequestsForDocumentId, email);
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: should be replaced with Java8 optionals

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 4]
```diff
@@ -163,23 +211,28 @@ public String addTodo(@NotNull Todo todo) throws SW360Exception {
...
-        Todo todo = todoRepository.get(todoId);
-
-        assertNotNull(license);
+    public RequestStatus addTodoToLicense(Todo todo, String licenseId, User user) throws SW360Exception {
         assertNotNull(todo);
-
+        License license = licenseRepository.get(licenseId);
         if (makePermission(license, user).isActionAllowed(RequestedAction.WRITE)) {
+            assertNotNull(license);
+            if(todo.isSetId() && todo.id.startsWith("tmp")) todo.unsetId();
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: Do not use inline if clauses

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 5]
```diff
@@ -189,11 +242,10 @@ public RequestStatus updateWhitelist(String licenseId, Set<String> whitelistTodo
         License license = licenseRepository.get(licenseId);
         assertNotNull(license);
 
-        if (makePermission(license, user).isActionAllowed(RequestedAction.WRITE)) {
-
-            String organisation = user.getDepartment();
+        String organisation = user.getDepartment();
+        String bu = SW360Utils.getBUFromOrganisation(organisation);
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: use `bussinesunit` as variable name

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 6]
```diff
@@ -288,9 +358,32 @@ public T apply(String input) {
...
+                            dbTodo.addToWhitelist(bu);
+                            todoRepository.update(dbTodo);
+                        }
+                        if (!todo.whitelist.contains(bu) && dbTodo.whitelist.contains(bu)) {
+                            dbTodo.whitelist.remove(bu);
+                            todoRepository.update(dbTodo);
+                        }
+                    }
+                } catch (SW360Exception e) {
+                    log.error("Error adding todo to database or updating whitelist.");
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: Please add more verbose debug information, i.e. `todo.id`

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java [hunk 7]
```diff
@@ -97,15 +100,15 @@ private void renderActionView(RenderRequest request, RenderResponse response) th
                 } else if (ACTION_DECLINE.equals(request.getParameter(ACTION))) {
                     client.refuseRequest(id);
 
-                    sessionMessage = "You have decline the previous moderation request";
+                    sessionMessage = "You have declined the previous moderation request";
                 } else if (ACTION_ACCEPT.equals(request.getParameter(ACTION))) {
-                    acceptModerationRequest(user, moderationRequest);
+                    acceptModerationRequest(user, UserCacheHolder.getUserFromEmail(moderationRequest.getRequestingUser()), moderationRequest);
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java]: You could better write something like
```
someUserEmail = moderationRequest.getRequestingUser()
someUser = UserCacheHolder.getUserFromEmail(someUserEmail)
acceptModerationRequest(user, someUser, moderationRequest);
```

File: backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java (hunk 2 above)
Comment (maximilianhuber) [inline backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ProjectDatabaseHandler.java]: Since this us used frequently, you could encapsulate this into a function call `moderationRequestOptional.get().isInprogressOrPending()`

File: libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/thrift/ThriftValidate.java [hunk 8]
```diff
@@ -68,6 +69,14 @@ public static void prepareTodo(Todo todo) throws SW360Exception {
             }
         }
 
+        if (!todo.isSetObligations()) {
```
Comment (maximilianhuber) [inline libraries/lib-datahandler/src/main/java/com/siemens/sw360/datahandler/thrift/ThriftValidate.java]: is inconsistent

File: frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp [hunk 9]
```diff
@@ -92,14 +92,30 @@
         var result = [];
 
         <core_rt:forEach items="${moderationRequests}" var="moderation">
+        <core_rt:set var="isOpenModerationRequest" value="${moderation.getModerationState().toString()== 'INPROGRESS' ||
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp]: see the comment above: create and call `moderation.isInprogressOrPending()`

File: backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java [hunk 10]
```diff
@@ -828,16 +828,10 @@ private void fillVendor(Release release) {
...
-            }
-        };
-
-        return FluentIterable.from(nullToEmptySet(release.getAttachments()))
-                .filter(isSourceAttachment)
-                .toSet();
+        return nullToEmptySet(release.getAttachments())
+                .stream()
+                .filter(input -> (input != null) && input.getAttachmentType() == AttachmentType.SOURCE)
+                .collect(Collectors.toSet());
```
Comment (maximilianhuber) [inline backend/src-common/src/main/java/com/siemens/sw360/datahandler/db/ComponentDatabaseHandler.java]: __Just a hint__: you could use the power of laziness to write equivalently
```
return nullToEmptySet(release.getAttachments())
        .stream()
        .filter(input -> input != null)
        .filter(input -> input.getAttachmentType() == AttachmentType.SOURCE)
        .collect(Collectors.toSet());
```

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 11]
```diff
@@ -75,6 +79,9 @@ public LicenseDatabaseHandler(String url, String dbName) throws MalformedURLExce
         riskRepository = new RiskRepository(db);
         riskCategoryRepository = new RiskCategoryRepository(db);
         licenseTypeRepository = new LicenseTypeRepository(db);
+
+        moderator = new LicenseModerator();
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: I don't think that this statement should be surrounded by newlines

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java [hunk 12]
```diff
@@ -445,6 +453,30 @@ private void prepareProject(RenderRequest request, User user, Project actual_pro
...
+        License actual_license = null;
+        User requestingUser = UserCacheHolder.getUserFromEmail(moderationRequest.getRequestingUser());
+        try {
+            LicenseService.Iface client = thriftClients.makeLicenseClient();
+            actual_license = client.getByID(moderationRequest.getDocumentId(),requestingUser.getDepartment());
+            request.setAttribute(PortalConstants.ACTUAL_LICENSE, actual_license);
+            List<Obligation> obligations = client.getAllObligations();
+            request.setAttribute(KEY_OBLIGATION_LIST, obligations);
+            request.setAttribute(KEY_LICENSE_DETAIL, actual_license);
+            request.setAttribute(SELECTED_TAB, request.getParameter(SELECTED_TAB));
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/moderation/ModerationPortlet.java]: What does this line do?

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/CompareTodos.java [hunk 13]
```diff
@@ -0,0 +1,194 @@
...
+            renderTodos(display, old, update);
+
+            String renderString = display.toString();
+
+            if (Strings.isNullOrEmpty(renderString)) {
+                renderString = "<h4> No changes in TODOs </h4>";
+            }
+
+            jspWriter.print(renderString);
+        } catch (Exception e) {
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/CompareTodos.java]: Why do you catch all exceptions here?

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/CompareTodos.java [hunk 14]
```diff
@@ -0,0 +1,194 @@
...
+
+    private void renderTodos(StringBuilder display, List<Todo> currentTodos, List<Todo> updateTodos) {
+
+        Map<String, Todo> currentTodoById = getTodosById(currentTodos);
+        Map<String, Todo> updateTodoById = getTodosById(updateTodos);
+
+        Set<String> currentTodoIds = currentTodoById.keySet();
+        Set<String> updateTodoIds = updateTodoById.keySet();
+
+        Set<String> addedTodoIds = Sets.difference(updateTodoIds, currentTodoIds);
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/tags/CompareTodos.java]: Is it verified, that `currentTodoIds` is always a subset of `updateTodoIds`?

File: libraries/importers/license-importer/src/test/java/com/siemens/sw360/importer/ConvertRecordTest.java [hunk 15]
```diff
@@ -130,7 +130,7 @@
 //
 //        assertEquals("6", todo.getId());
 //        assertEquals("Todo6", todo.getText());
-//        assertFalse(todo.isDevelopement());
+//        assertFalse(todo.isDevelopment());
```
Comment (maximilianhuber) [inline libraries/importers/license-importer/src/test/java/com/siemens/sw360/importer/ConvertRecordTest.java]: Remove this file? It is completly commented out

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 16]
```diff
@@ -280,17 +352,39 @@ private void filterTodoWhiteList(String organisation, List<Todo> todos) {
...
-                return map.get(input);
+        return ids
+                .stream()
+                .map(input -> map.get(input))
+                .filter(input -> input !=null)
+                .collect(Collectors.toList());
+    }
+
+    public RequestStatus updateLicense(License moderatedLicense, User user, User requestingUser) {
+        if (PermissionUtils.isClearingAdmin(user)) {
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: This excludes the admin? I think it would be better to use `PermissionUtils.isUserAtLeast(...)`

File: backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 17]
```diff
@@ -280,17 +352,39 @@ private void filterTodoWhiteList(String organisation, List<Todo> todos) {
...
+                if (todo.isSetId() && todo.id.startsWith("tmp")) {
+                    todo.unsetId();
+                    try {
+                        String todoDatabaseId = addTodo(todo);
+                        dbLicense.addToTodoDatabaseIds(todoDatabaseId);
+                    } catch (SW360Exception e) {
+                        log.error("Error adding todo to database.");
+                    }
+                } else if (todo.isSetId()) {
+                        Todo dbTodo = todoRepository.get(todo.id);
```
Comment (maximilianhuber) [inline backend/src/src-licenses/src/main/java/com/siemens/sw360/licenses/db/LicenseDatabaseHandler.java]: indentation error

File: backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/db/ModerationDatabaseHandler.java [hunk 18]
```diff
@@ -168,6 +183,47 @@ public void createRequest(Project project, String user, Boolean isDeleteRequest)
         addOrUpdate(request);
     }
 
+    public void createRequest(License license, String user, String department, Boolean isDeleteRequest) {
```
Comment (maximilianhuber) [inline backend/src/src-moderation/src/main/java/com/siemens/sw360/moderation/db/ModerationDatabaseHandler.java]: The variable `isDeleteRequest` is unused

File: frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/licenses/LicensesPortlet.java [hunk 19]
```diff
@@ -92,14 +95,36 @@ public void doView(RenderRequest request, RenderResponse response) throws IOExce
...
+
+                    List<Todo> allTodos = nullToEmptyList(moderationLicense.getTodos());
+                    List<Todo> addedTodos = allTodos
+                            .stream()
+                            .filter(todo -> todo.id.startsWith("tmp"))
+                            .collect(Collectors.toList());
+                    List<Todo>  currentTodos =  allTodos
+                            .stream()
+                            .filter(todo -> !todo.id.startsWith("tmp"))
+                            .collect(Collectors.toList());
```
Comment (maximilianhuber) [inline frontend/sw360-portlet/src/main/java/com/siemens/sw360/portal/portlets/licenses/LicensesPortlet.java]: you could replace the lines above by something like:
```
List<Todo> allTodos = nullToEmptyList(moderationLicense.getTodos());
List<Todo> addedTodos = new [??](); 
List<Todo> currentTodos = new [??]();
allTodos.forEach(todo -> ((todo.id.startsWith("tmp")) ? addedTodos : currentTodos).add(x));
```

**Comment by mcjaeger** [comment]
tested and looks good (tested with vagrant user list):
1. user creates moderation request and admin approves it and user can see the change
2. user creates moderation request ad admin2 cannot see it
3. admin creates a new todo and appears in list
4. user creates a moderation request clearing admin can approve it.
5. more playing around like this - looks good!

could be merged IMHO.
